name: 2023 tests

on:
  push:
    branches:
      - "2023"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          ref: "2023"

      - name: setup go
        uses: actions/setup-go@main
        with:
          go-version: "stable"

      - name: run tests
        run: go test -v ./...
